config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  resources :nota
  root 'pages#home'
  devise_for :users
 


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/notum.rb
class Notum < ApplicationRecord
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role:[:user, :moderador, :admin]
  after_initialize:set_default_role, :if => :new_record?
  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nota_controller.rb
class NotaController < ApplicationController
  before_action :set_notum, only: %i[ show edit update destroy ]

  # GET /nota or /nota.json
  def index
    @nota = Notum.all
  end

  # GET /nota/1 or /nota/1.json
  def show
  end

  # GET /nota/new
  def new
    @notum = current_user.notas.new
  end

  # GET /nota/1/edit
  def edit
  end

  # POST /nota or /nota.json
  def create
    @notum = Notum.new(notum_params)

    respond_to do |format|
      if @notum.save
        format.html { redirect_to notum_url(@notum), notice: "Notum was successfully created." }
        format.json { render :show, status: :created, location: @notum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @notum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nota/1 or /nota/1.json
  def update
    respond_to do |format|
      if @notum.update(notum_params)
        format.html { redirect_to notum_url(@notum), notice: "Notum was successfully updated." }
        format.json { render :show, status: :ok, location: @notum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @notum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nota/1 or /nota/1.json
  def destroy
    @notum.destroy

    respond_to do |format|
      format.html { redirect_to nota_url, notice: "Notum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notum
      @notum = Notum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notum_params
      params.require(:notum).permit(:user_id, :conteudo)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    @tweets = current_user.tweets.all
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = current_user.tweets.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = current_user.tweets.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:user_id, :conteudo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nota_helper.rb
module NotaHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diario</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    </head>
    
  <body>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark" >
      <div class="container-fluid">
        <%= link_to "Diario", root_path, class: 'nav-link' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Tweets", tweets_path, 'data-turbo-method': :get, class:'nav-link' %>
            </li>
                       
            </li>
            <li class="nav-item">
              <%= link_to "?", root_path, class: 'nav-link' %>
            </li>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Dropdown link
          </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
          </ul>
          <% if current_user%>
              <li class="nav-item">
              <%= link_to "Deslogar", destroy_user_session_path, 'data-turbo-method': :delete, class:'btn btn-danger' %>  
            <% end %> 
        </div>
      </div>
    </nav>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    
  </body>
</html>

app/views/nota/_form.html.erb
<%= form_with(model: notum) do |form| %>
  <% if notum.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(notum.errors.count, "error") %> prohibited this notum from being saved:</h2>

      <ul>
        <% notum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :conteudo, style: "display: block" %>
    <%= form.text_area :conteudo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/nota/_notum.html.erb
<div id="<%= dom_id notum %>">
  <p>
    <strong>User:</strong>
    <%= notum.user_id %>
  </p>

  <p>
    <strong>Conteudo:</strong>
    <%= notum.conteudo %>
  </p>

</div>

app/views/nota/edit.html.erb
<h1>Editing notum</h1>

<%= render "form", notum: @notum %>

<br>

<div>
  <%= link_to "Show this notum", @notum %> |
  <%= link_to "Back to nota", nota_path %>
</div>

app/views/nota/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Nota</h1>

<div id="nota">
  <% @nota.each do |notum| %>
    <%= render notum %>
    <p>
      <%= link_to "Show this notum", notum %>
    </p>
  <% end %>
</div>

<%= link_to "New notum", new_notum_path %>

app/views/nota/new.html.erb
<h1>New notum</h1>

<%= render "form", notum: @notum %>

<br>

<div>
  <%= link_to "Back to nota", nota_path %>
</div>

app/views/nota/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @notum %>

<div>
  <%= link_to "Edit this notum", edit_notum_path(@notum) %> |
  <%= link_to "Back to nota", nota_path %>

  <%= button_to "Destroy this notum", @notum, method: :delete %>
</div>

app/views/pages/home.html.erb
<h1>Pagina Inicial</h1>
<p>Faça login para acessar o projeto</p>

<% if current_user%>
    <h1>Você é um <%= current_user.role%></h1>
    <% if current_user.admin? %>
    <span> Tem <%= User.count %> logadas no projeto </span>
    <% end %>
    <p> Bem vindo <%= current_user.email %></p>
    <p>
    Você logou com sucesso, agora pode interagir com o projeto
    </p>
    <%= link_to "Deslogar", destroy_user_session_path,'data-turbo-method': :delete%>
<% else %>
    <p> Você não esta logado </p>
    <p>
        <%= link_to "Logar", new_user_session_path%><br>
        <%= link_to "Cadastrar", new_user_registration_path%>
    </p>
<% end %>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div>
    <%= form.label :conteudo, style: "display: block" %>
    <%= form.text_area :conteudo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
  <p>
    <strong>User:</strong>
    <%= tweet.user.email %>
  </p>

  <p>
    <strong>Conteudo:</strong>
    <%= tweet.conteudo %>
  </p>

</div>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tweets</h1>

<div id="tweets">
  <% @tweets.each do |tweet| %>
    <%= render tweet %>
    <p>
      <%= link_to "Show this tweet", tweet %>
    </p>
  <% end %>
</div>

<%= link_to "New tweet", new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Edit this tweet", edit_tweet_path(@tweet) %> |
  <%= link_to "Back to tweets", tweets_path %>

  <%= button_to "Destroy this tweet", @tweet, method: :delete %>
</div>